receivers:
    otlp:
        protocols:
            grpc:
                endpoint: 127.0.0.1:4317
            http:
                endpoint: 127.0.0.1:4318
exporters:
    logging:
        loglevel: debug
    validator:
service:
    pipelines:
        traces:
            receivers: [otlp]
            exporters: [validator]
        metrics:
            receivers: [otlp]
            exporters: [validator]
        logs:
            receivers: [otlp]
            exporters: [validator]
